apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: webservice-deployment
spec:
  selector:
    matchLabels:
      app: webservice
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
      - name: webservice
        image: webservice
        imagePullPolicy: Never
        ports:
        - containerPort: 80
