version: '2'

services:
  database:
    build:
      context: ./
      dockerfile: DockerfileMysql
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hola
  webservice:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: webservice
    ports:
      - "8080:80"
    links:
      - "database"