apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice-deployment
  labels:
    app: webservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
      - name: webservice
        image: webservice
        imagePullPolicy: Never
        ports:
        - containerPort: 8080